    name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    name: Build project
      run: dotnet publish -c Release -o build

    name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp://2805.somee.com/www.2805.somee.com
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        local-dir: "build/"
        server-dir: "/wwwroot/"
