name: Deploy to somee FTP

on:
  push:
    branches: [ "main" ]   # branch nào push thì deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp://155.254.244.39/www.2805.somee.com
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        local-dir: "./"          
        server-dir: "/wwwroot/"   
