name: Deploy to somee FTP

on:
  push:
    branches: [ "main" ]   # branch nào push thì deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.your_somee_hostname_here
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        local-dir: "./"           # thư mục build local (gốc repo)
        server-dir: "/wwwroot/"   # thư mục trên somee (tùy hosting)
